
COSMIC_DIR = 'COSMIC'

COSMIC_GENOME_SIGS_URL='https://obj.umiacs.umd.edu/mutation-signature-explorer/signatures/COSMIC/processed/cosmic-signatures.SBS-96.tsv'
# SIG_PROFILER_EXOME_SIGS_URL='https://obj.umiacs.umd.edu/mutation-signature-explorer/signatures/PCAWG/processed/sigProfiler-exome_signatures.SBS-96.tsv'
# Files
RAW_COSMIC_SIGNATURES = join(COSMIC_DIR, 'raw-cosmic-signatures.tsv')
COSMIC_SIGNATURES = join(COSMIC_DIR, 'cosmic-signatures.tsv')
STM_EXOME_SIGNATURES_FILE=join(OUTPUT_DIR, 'stm-exome-signatures_{covariates}_{K}_{project}.tsv')
STM_GENOME_SIGNATURES_FILE=join(OUTPUT_DIR, 'stm-genome-signatures_{covariates}_{K}_{project}.tsv')
SIG_COSINE_PLOT=join(OUTPUT_DIR, "stm-cosine-similarity_{covariates}_{K}_{project}.pdf")
SIG_COSINE_SIM=join(OUTPUT_DIR, "stm-cosine-similarity_{covariates}_{K}_{project}.tsv")

SIG_PLOT=join(OUTPUT_DIR, "stm-signatures_{covariates}_{K}_{project}.pdf")

rule plot_signatures:
    input:
        STM_GENOME_SIGNATURES_FILE,
        STM_ALL_NORMALIZED_EXPOSURES_FILE,
        ALL_MC_FILE
    output:
        SIG_PLOT
    script:
        "src/plot_sigs.py"

rule calculate_cosine_similarity:
    input:
        COSMIC_SIGNATURES,
        STM_GENOME_SIGNATURES_FILE
    output:
        SIG_COSINE_PLOT,
        SIG_COSINE_SIM
    script:
        "src/plot_cosine_similarity.py"



rule download_cosmic_signatures:
    params:
        url=COSMIC_GENOME_SIGS_URL
    output:
        COSMIC_SIGNATURES
    shell:
        'wget -O {output} {params.url}'
