from os.path import join

COSMIC_DIR = 'COSMIC'
OUTPUT_DIR = 'processed'

COSMIC_GENOME_SIGS_URL='https://obj.umiacs.umd.edu/mutation-signature-explorer/signatures/COSMIC/processed/cosmic-signatures.SBS-96.tsv'
# Files
COSMIC_SIGNATURES = join(COSMIC_DIR, 'cosmic-signatures.tsv')
STM_EXOME_SIGNATURES_FILE=join(OUTPUT_DIR, '{method}-exome-signatures_{covariates}_{K}_{project}.tsv')
STM_GENOME_SIGNATURES_FILE=join(OUTPUT_DIR, '{method}-genome-signatures_{covariates}_{K}_{project}.tsv')
SIG_COSINE_PLOT=join(OUTPUT_DIR, "{method}-cosine-similarity_{covariates}_{K}_{project}.pdf")
SIG_COSINE_SIM=join(OUTPUT_DIR, "{method}-cosine-similarity_{covariates}_{K}_{project}.tsv")

SIG_PLOT=join(OUTPUT_DIR, "{method}-signatures_{covariates}_{K}_{project}.pdf")

rule plot_signatures:
    input:
        STM_EXOME_SIGNATURES_FILE,
        STM_ALL_NORMALIZED_EXPOSURES_FILE,
        MC_FILE
    output:
        SIG_PLOT
    script:
        "src/plot_sigs.py"

rule calculate_COSMIC_cosine_similarity:
    input:
        COSMIC_SIGNATURES,
        COSMIC_SIGNATURES,
    output:
        join(OUTPUT_DIR, "COSMIC-cosine-similarity.pdf"),
        join(OUTPUT_DIR, "COSMIC-cosine-similarity.tsv"),
    script:
        "src/plot_cosine_similarity.py"

rule calculate_cosine_similarity:
    input:
        COSMIC_SIGNATURES,
        STM_EXOME_SIGNATURES_FILE
    output:
        SIG_COSINE_PLOT
    script:
        "src/plot_cosine_similarity.py"

rule download_cosmic_signatures:
    params:
        url=COSMIC_GENOME_SIGS_URL
    output:
        COSMIC_SIGNATURES
    shell:
        'wget -O {output} {params.url}'
