from os.path import join

include: "../Snakefile"

wildcard_constraints:
    total_n_samples="\d+",
    n_samples="\d+",
    iter_num="\d+"

# Directories
COSMIC_DIR = 'COSMIC'
OUTPUT_DIR = 'processed'

# URLs
SBS96_COUNT_URL = "https://obj.umiacs.umd.edu/mutation-signature-explorer/mutations/PanCanAtlas/processed/counts/counts.TCGA-BRCA_BRCA_mc3.v0.2.8.WXS.SBS-96.tsv"
COSMIC_GENOME_SIGS_URL='https://obj.umiacs.umd.edu/mutation-signature-explorer/signatures/COSMIC/processed/cosmic-signatures.SBS-96.tsv'

# Files
# input to simulate_dmr_data
N_MUTATION_DISTRIBUTION_FILE=join(OUTPUT_DIR, "TCGA-BRCA-nmutations.tsv")
SBS96_COUNT_FILE=join(OUTPUT_DIR, 'TCGA-BRCA-sbs96.tsv')
FEATURES_FILE=join(OUTPUT_DIR, "{total_n_samples}_{iter_num}_features.tsv")
LAMBDA_FILE=join(OUTPUT_DIR, "lambdas.csv")
COSMIC_SIGNATURES = join(COSMIC_DIR, 'cosmic-signatures.tsv')
# output of simulate_dmr_data
DOC_FILE=join(OUTPUT_DIR, "{total_n_samples}_{iter_num}_documents.tsv")
MODEL_FILE=join(OUTPUT_DIR, "{total_n_samples}_{iter_num}_model.npz")
MUTATION_COUNT_MATRIX_FILE=join(OUTPUT_DIR, "{total_n_samples}_{iter_num}_mutation_count.tsv")
GT_SIGNATURES_FILE=join(OUTPUT_DIR, "{total_n_samples}_{iter_num}_signatures.tsv")
GT_EXPOSURES_FILE=join(OUTPUT_DIR, "{total_n_samples}_{iter_num}_exposures.tsv")

EXP_FEATURES_FILE=join(OUTPUT_DIR, "{n_samples}_{total_n_samples}_{iter_num}_features.tsv")
EXP_MUTATION_COUNT_MATRIX_FILE=join(OUTPUT_DIR, "{n_samples}_{total_n_samples}_{iter_num}_mutation_count.tsv")
EXP_GT_EXPOSURES_FILE=join(OUTPUT_DIR, "{n_samples}_{total_n_samples}_{iter_num}_exposures.tsv")

# parameters
seed = "123456"
ACTIVE_SIGS= [1, 2, 3, 5]

rule all:
    input:
        expand(EXP_FEATURES_FILE, total_n_samples=250, iter_num=0, n_samples=50),
        expand(EXP_MUTATION_COUNT_MATRIX_FILE, total_n_samples=250, iter_num=0, n_samples=50),
        expand(EXP_GT_EXPOSURES_FILE, total_n_samples=250, iter_num=0, n_samples=50),

rule subsample_dmr_data:
    input:
        FEATURES_FILE,
        MUTATION_COUNT_MATRIX_FILE,
        GT_EXPOSURES_FILE
    output:
        EXP_FEATURES_FILE,
        EXP_MUTATION_COUNT_MATRIX_FILE,
        EXP_GT_EXPOSURES_FILE
    script:
        "src/subsample_dmr_data.py"

rule simulate_dmr_data:
    input:
        topics_file=COSMIC_SIGNATURES,
        features_file=FEATURES_FILE,
        lambda_file=LAMBDA_FILE,
        n_mutation_distribution=N_MUTATION_DISTRIBUTION_FILE
    output:
        documents_file=DOC_FILE,
        model_file=MODEL_FILE,
        matrix_file=MUTATION_COUNT_MATRIX_FILE,
        signature_file=GT_SIGNATURES_FILE,
        exposures_file=GT_EXPOSURES_FILE
    shell:
        "python src/sim_dmr_data.py -tf {input.topics_file} -ff {input.features_file}\
        -l {input.lambda_file} -enm {input.n_mutation_distribution} -at {ACTIVE_SIGS}\
        -n {wildcards.total_n_samples} -od {output.documents_file} -om {output.model_file} \
        -omf {output.matrix_file} -os {output.signature_file} -oe {output.exposures_file} \
        -ni {wildcards.iter_num}"

rule generate_BRCAness_data:
    params:
        seed=seed
    output:
        FEATURES_FILE
    script:
        "src/generate_clinical_data.py"

rule generate_lambdas:
    output:
        LAMBDA_FILE
    script:
        "src/generate_handcrafted_lambdas.py"

# Download and process COSMIC signatures
rule download_cosmic_signatures:
    params:
        url=COSMIC_GENOME_SIGS_URL
    output:
        COSMIC_SIGNATURES
    shell:
        'wget -O {output} {params.url}'

rule create_n_mutations_distribution_file:
    input:
        SBS96_COUNT_FILE
    output:
        N_MUTATION_DISTRIBUTION_FILE
    script:
        "src/create_n_mutations_empirical_distribution.py"

rule download_cancer_type_counts:
    params:
        SBS96_COUNT_URL
    output:
        SBS96_COUNT_FILE
    shell:
        "wget -O {output} {params}"
