from os.path import join

OUTPUT_DIR = 'processed'
RAW_DIR = 'raw'

wildcard_constraints:
    cancer_type="[A-Z]+"

subworkflow dinucsworkflow:
    workdir:
        "../TCGA-dinucs"

# URLS
SBS96_COUNT_URL = "https://obj.umiacs.umd.edu/mutation-signature-explorer/mutations/PanCanAtlas/processed/counts/counts.TCGA-{cancer_type}_{cancer_type}_mc3.v0.2.8.SBS-96.tsv"
BRCA_SUBTYPE_URL = "https://www.cell.com/cms/10.1016/j.ccell.2018.03.014/attachment/ca04da67-7e4b-4930-8eb8-5c941eebf6b7/mmc4.xlsx"
CLINICAL_URL="https://obj.umiacs.umd.edu/mutation-signature-explorer/clinical/PanCanAtlas/processed/clinical.TCGA_{cancer_type}.tsv"

# Raw input files
RAW_HR_BIALLELIC_INACTIVATION_FILE=join(RAW_DIR, "TCGA-{cancer_type}_HR-biallelic-inactivation_Riaz2017.tsv")
RAW_DDR_SILENCING_FILE=join(RAW_DIR, "TCGA-{cancer_type}_Silencing_Knijnenburg2018.tsv")
RAW_DDR_MUTATED_FILE=join(RAW_DIR, "TCGA-{cancer_type}_Mutations_Knijnenburg2018.tsv")
RAW_DDR_DELETED_FILE=join(RAW_DIR, "TCGA-{cancer_type}_Deletions_Knijnenburg2018.tsv")
RAW_LST_FILE=join(RAW_DIR, "TCGA-{cancer_type}_LST_Riaz2017.tsv")
RAW_POLE_FILE=join(RAW_DIR, "classify_POLE_in_TCGA-BRCA_mc3.v0.2.8.SBS.tsv") # update later when fixed
RAW_MUTATION_COUNT_MATRIX_FILE=join(RAW_DIR, "TCGA-{cancer_type}_mutation_count.tsv")
RAW_BRCA_SUBTYPE_FILE=join(RAW_DIR, "TCGA-BRCA_subtype_info.xlsx")
RAW_MSI_CLASSIFICATION_FILE=join(RAW_DIR, "TCGA-{cancer_type}_msi-classification_Hause2016.tsv")
RAW_CLINICAL_FILE=join(RAW_DIR, "TCGA-{cancer_type}_clinical.tsv")
RAW_APOBEC_FILE=join(RAW_DIR, "apobec3_gene_expression.tsv")
RAW_APOBEC_BINARY_FILE=join(RAW_DIR, "TCGA-{cancer_type}_APOBEC3_expression_cBioPortal.tsv")
RAW_ALEXANDROV2018_DNP_FILE=join(RAW_DIR, "TCGA_dinucs_Alexandrov2018.csv")
FIREHOSE_DNP_FILE = join(OUTPUT_DIR, "gdac.broadinstitute.org_{cancer_type}.Mutation_Packager_Oncotated_Calls.Level_3.2016012800.0.0" + ".patient_DNP_map.tsv")
CANCERTYPE_ALEXANDROV2018_DNP_FILE=join(RAW_DIR, "TCGA-{cancer_type}_dinucs_Alexandrov2018.tsv")
# Processed files
POLE_EXO_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_POLE-exo_feature.tsv")
HR_FEATURE_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_HRd_feature.tsv")
LST_FEATURE_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_LST_feature.tsv")
HR_BIALLELIC_INACTIVATION_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_HR-biallelic-inactivation_Riaz2017.tsv")
DDR_SILENCING_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_Silencing_Knijnenburg2018.tsv")
DDR_MUTATED_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_Mutated_Knijnenburg2018.tsv")
DDR_DELETED_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_Deleted_Knijnenburg2018.tsv")
BRCA_SUBTYPE_FILE=join(OUTPUT_DIR, "TCGA-BRCA_subtype.tsv")
MSI_CLASSIFICATION_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_msi-classification_Hause2016.tsv")
CLINICAL_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_clinical.tsv")
APOBEC_EXP_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_APOBEC3_PanCanAtlas.tsv")
APOBEC_BINARY_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_APOBEC3_cBioPortal.tsv")
CC_TT_DINUCS_FILE=join(OUTPUT_DIR, "TCGA-{cancer_type}_dinucs.tsv")


rule split_dinucs_by_cancertype:
    input:
        RAW_MUTATION_COUNT_MATRIX_FILE,
        RAW_ALEXANDROV2018_DNP_FILE
    output:
        CANCERTYPE_ALEXANDROV2018_DNP_FILE
    script:
        "src/split_dinucs_by_cancertype.py"

rule combine_dinucs:
    input:
        CANCERTYPE_ALEXANDROV2018_DNP_FILE,
        dinucsworkflow(FIREHOSE_DNP_FILE)
    output:
        CC_TT_DINUCS_FILE
    script:
        "src/combine_dinucs.py"

rule clean_clinical_file:
    input:
        RAW_CLINICAL_FILE
    output:
        CLINICAL_FILE
    script:
        "src/clean_clinical_file.py"

rule clean_msi_file:
    input:
        RAW_MSI_CLASSIFICATION_FILE
    output:
        MSI_CLASSIFICATION_FILE
    script:
        "src/clean_msi_file.py"

rule clean_apobec_exp_file:
    input:
        RAW_APOBEC_FILE,
        RAW_MUTATION_COUNT_MATRIX_FILE
    output:
        APOBEC_EXP_FILE
    script:
        "src/clean_APOBEC_exp.py"

rule clean_apobec_binary_file:
    input:
        RAW_APOBEC_BINARY_FILE,
    output:
        APOBEC_BINARY_FILE
    script:
        "src/clean_APOBEC_binary.py"

rule clean_pole_file:
    input:
        RAW_POLE_FILE,
        RAW_MUTATION_COUNT_MATRIX_FILE
    output:
        POLE_EXO_FILE
    script:
        "src/clean_pole_mutations.py"

rule clean_biallelic_hr_inactivation:
    input:
        RAW_HR_BIALLELIC_INACTIVATION_FILE
    output:
        HR_BIALLELIC_INACTIVATION_FILE
    script:
        "src/clean_hr_biallelic_inactivations.py"

rule clean_epigenetic_silencing_file:
    input:
        RAW_DDR_SILENCING_FILE
    output:
        DDR_SILENCING_FILE
    script:
        "src/clean_epigenetic_silencing.py"

rule clean_mutated_file:
    input:
        RAW_DDR_MUTATED_FILE
    output:
        DDR_MUTATED_FILE
    script:
        "src/clean_Knij_mutated.py"

rule clean_deletion_file:
    input:
        RAW_DDR_DELETED_FILE
    output:
        DDR_DELETED_FILE
    script:
        "src/clean_Knij_deleted.py"

rule combine_hr_file:
    input:
        RAW_HR_BIALLELIC_INACTIVATION_FILE,
        RAW_DDR_SILENCING_FILE
    output:
        HR_FEATURE_FILE
    script:
        "src/combine_hr_inactivations.py"

rule clean_lst_file:
    input:
        RAW_LST_FILE
    output:
        LST_FEATURE_FILE
    script:
        "src/clean_lst_file.py"

rule clean_BRCA_subtype_info:
    input:
        RAW_BRCA_SUBTYPE_FILE
    output:
        BRCA_SUBTYPE_FILE
    script:
        "src/clean_BRCA_subtype_feature.py"

rule download_clinical_data:
    params:
        CLINICAL_URL
    output:
        RAW_CLINICAL_FILE
    shell:
        "wget -O {output} {params}"

rule download_BRCA_subtype_info:
    params:
        BRCA_SUBTYPE_URL
    output:
        RAW_BRCA_SUBTYPE_FILE
    shell:
        "wget -O {output} {params}"

rule download_sbs_count_data:
    params:
        SBS96_COUNT_URL
    output:
        RAW_MUTATION_COUNT_MATRIX_FILE
    shell:
        "wget -O {output} {params}"
